{% set name = "FigureGenerator" %}
{% set version = "0.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/FigureGenerator-{{ version }}.tar.gz
  sha256: 14c74f76e8c0acfad16e0b7447ed1f5d43344ef22268e04adbb9d4490eda27ba

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - black
    - coverage
    - ipywidgets
    - numpy >=1.19.2
    - psutil
    - pytest
    - python >=3.6
    - simpleitk >=2.1.0

test:
  imports:
    - FigureGenerator
  requires:
    - pip

about:
  home: https://pypi.org/project/FigureGenerator/
  summary: Making screenshots for presentations and manuscripts.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
